[build]
# Force using only baseline x86_64 instructions for broader compatibility
# Use the most generic CPU target possible
rustflags = ["-C", "target-cpu=generic", "-C", "target-feature=-sse3,-ssse3,-sse4.1,-sse4.2,-avx,-avx2,-fma,-f16c"]

[env]
# Disable ALL CPU-specific optimizations in the C++ build
# Use only the most basic x86-64 instructions
CFLAGS = "-march=x86-64 -mtune=generic -mno-sse3 -mno-ssse3 -mno-sse4 -mno-sse4.1 -mno-sse4.2 -mno-avx -mno-avx2 -mno-fma -mno-f16c"
CXXFLAGS = "-march=x86-64 -mtune=generic -mno-sse3 -mno-ssse3 -mno-sse4 -mno-sse4.1 -mno-sse4.2 -mno-avx -mno-avx2 -mno-fma -mno-f16c"