[build]
# Force using only baseline x86_64 instructions for broader compatibility
rustflags = ["-C", "target-cpu=x86-64"]

[env]
# Disable CPU-specific optimizations in the C++ build
CFLAGS = "-march=x86-64 -mtune=generic"
CXXFLAGS = "-march=x86-64 -mtune=generic"